config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "home#index"
  resources :albums do 
    resources :photos, :except => [ :delete ]
  end
  delete '/albums/:album_id/photos/:id', to: 'photos#destroy', as: 'delete_album_photo'
  resources :profiles

  get '*all', to: 'application#check_bad_routes', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }

end

app/models/profile.rb
class Profile < ApplicationRecord
	validates :name, presence: true, length: { in: 2..20 }

	belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]
  before_action :check_profile, except: %i[ edit update ]

  # GET /profiles or /profiles.json
  def index
    redirect_to current_user.profile
    # @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    @profile = current_user.profile
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
      @profile = current_user.profile
    respond_to do |format|
      if @profile.update profile_params
        format.html { redirect_to profile_path(@profile), notice: "Profile updated!" }
        format.json { render :edit, status: :ok, location: @profile }
      else
        format.html { redirect_to edit_profile_path, flash: { error: "Profile could not be updated!" } }
        format.json { render json: @profile.errors.messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def check_profile
      if !current_user.profile.name.present?
        flash.notice = 'First update your profile'
        redirect_to edit_profile_path(current_user.profile)
      end
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:name)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, requred:'', class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success'%>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<div class="card w-75 m-auto p-4">
  <%= render 'form', profile: @profile %>
</div>

<%= link_to 'Back', profile_path, class: 'btn btn-secondary text-white' %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>
<br/>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<section class="bg-light">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 mb-4 mb-sm-5">
        <div class="card card-style1 border-0">
          <div class="card-body p-1-9 p-sm-2-3 p-md-6 p-lg-7">
            <div class="row align-items-center">
              <div class="col-lg-6 mb-4 mb-lg-0">
                <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="...">
              </div>
              <div class="col-lg-6 px-xl-10">
                <div class="bg-secondary w-100 d-lg-inline-block py-1-9 px-1-9 px-sm-6 mb-1-9 rounded">
                  <h3 class="h2 text-white mb-0"><%= @profile.name %></h3>
                  <span class="text-primary">Logged in User</span>
                </div>
                <ul class="list-unstyled mb-1-9">
                  <li class="mb-2 mb-xl-3 display-28"><span class="display-26 text-secondary me-2 font-weight-600">Position:</span> User</li>
                  <li class="mb-2 mb-xl-3 display-28"><span class="display-26 text-secondary me-2 font-weight-600">Skill:</span> RoR, HTML, AngularJS</li>
                  <li class="mb-2 mb-xl-3 display-28"><span class="display-26 text-secondary me-2 font-weight-600">Email:</span> <%= @profile.user.email %></li>
                  <li class="display-28"><span class="display-26 text-secondary me-2 font-weight-600">Phone:</span> 11215614586</li>
                </ul>
                <ul class="social-icon-style1 list-unstyled mb-0 ps-0">
                  <li><a href="#!"><i class="ti-twitter-alt"></i></a></li>
                  <li><a href="#!"><i class="ti-facebook"></i></a></li>
                  <li><a href="#!"><i class="ti-pinterest"></i></a></li>
                  <li><a href="#!"><i class="ti-instagram"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-12 mb-4 mb-sm-5">
        <div>
          <span class="section-title text-primary mb-3 mb-sm-4">About Me</span>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
          <p class="mb-0"> It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        </div>
      </div>
    </div>
    <%= link_to 'Edit', edit_profile_path(@profile), class: 'btn btn-primary text-white float-right px-5' %>
  </div>
</section>