config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "home#index"
  resources :albums do 
    resources :photos, :except => [ :delete ]
  end
  delete '/albums/:album_id/photos/:id', to: 'photos#destroy', as: 'delete_album_photo'
  resources :profiles

  get '*all', to: 'application#check_bad_routes', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }

end

app/views/shared/_alerts.html.erb
<div id="successMessage" class="alert alert-warning alert-dismissible fade show position-absolute m-auto w-25 l-0 r-0" role="alert">
  <%= notice %>
  <%= alert %> 
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/shared/_footer.html.erb
<div class="container-fluid mt-2 bg-dark">
	<h2 class="text-white mb-0 text-center p-2">Footer</h2>
</div>

app/views/shared/_header.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
	<%= link_to 'Image Sharing App', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      		<%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to 'My Albums', albums_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to 'My Profile', profile_path(current_user.profile), class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <ul class="nav list-inline mb-0">
    	<% if user_signed_in? %>
	      <li class="nav-item">
	      	<%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
	      </li>
      <% else %>
        <li class="nav-item">
        	<%= link_to 'Login', user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
        	<%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>