config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "home#index"
  resources :albums do 
    resources :photos, :except => [ :delete ]
  end
  delete '/albums/:album_id/photos/:id', to: 'photos#destroy', as: 'delete_album_photo'
  resources :profiles

  get '*all', to: 'application#check_bad_routes', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }

end

app/models/album.rb
class Album < ApplicationRecord
	validates :name, presence: true, length: { in: 2..20 }
	validates_length_of :photos, maximum: 24

	belongs_to :user
	has_many :photos, dependent: :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]
  before_action :check_profile
  before_action :check_owner, only: [:edit, :update, :destroy]

  # GET /albums or /albums.json
  def index
    @albums = current_user.albums
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = current_user.albums.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums or /albums.json
  def create
    @album = current_user.albums.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to albums_path, notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to albums_path, notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    def check_profile
      if !current_user.profile.name.present?
        flash.notice = 'First update your profile'
        redirect_to edit_profile_path(current_user.profile)
      end
    end

    def check_owner
     unless @album.user_id == current_user.id
      flash[:notice] = 'Access denied'
      redirect_to albums_path
     end
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:name, :user_id, photos_attributes: [:image, :caption, :album_id])
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, required:'', class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>
<div class="card w-75 m-auto p-4">
	<%= render 'form', album: @album %>
</div>

<%= link_to 'Show', @album, class: 'btn btn-info text-white' %>
<%= link_to 'Back', albums_path, class: 'btn btn-secondary text-white' %>

app/views/albums/index.html.erb
<div class="border rounded my-4 px-2 d-flex justify-content-between">
  <div class="align-items-center d-inherit">
    <h3><%= current_user.profile.name %>'s All Albums</h3>
  </div>
  <div>
    <%= link_to 'Create New Album', new_album_path, class:'btn btn-secondary text-white my-3' %>
  </div>
</div>
<% if @albums.count != 0 %>
  <div class="row">
    <% @albums.each do |album| %>
    <div class="col-md-3 my-3">
      <div class="card">
        <h5 class="card-header text-center pb-0"><%= album.name %> <br> <span class="font-weight-normal text-muted text-right font-12">Created at:- <%= album.created_at.strftime("%d-%m-%Y") %></span></h5>
        <% if album.photos.count < 25 %>
          <%= link_to image_tag("folder.png", class: 'card-img-overlay position-relative card-img-top z-99'), new_album_photo_path(album) %>
        <% else %>
          <%= link_to image_tag("closed_folder.png", class: 'card-img-overlay position-relative card-img-top z-99') %>
        <% end %>
        <div class="text-center card-body pb-0">
          <p class="card-text">Total no. of photos - <%= album.photos.count %></p>
        </div>
        <div class="card-footer text-center card-body px-0">
          <% if album.photos.count < 25 %>
            <%= link_to 'Show Album', album_photos_path(album), class: 'card-link btn-sm btn-primary text-white' %>
          <% end %>
          <%= link_to 'Edit', edit_album_path(album), class: 'card-link btn-sm btn-secondary text-white' %>
          <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure? All Associated Photos will be destroyed' }, class: 'card-link btn-sm btn-danger text-white' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
<% else %>
  <h3 class="text-center">No album yet!</h3>
<% end %>

app/views/albums/new.html.erb
<h1>New Album</h1>
<div class="card w-75 m-auto p-4">
	<%= render 'form', album: @album %>
</div>

<%= link_to 'Back', albums_path, class: 'btn btn-secondary text-white' %>

app/views/albums/show.html.erb
<div class="card w-75 m-auto p-4">
  <p>
    <strong>Name:</strong>
    <%= @album.name %>
  </p>
</div>
<%= link_to 'Edit', edit_album_path(@album), class: 'btn btn-info text-white' %>
<%= link_to 'Back', albums_path, class: 'btn btn-secondary text-white' %>