config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "home#index"
  resources :albums do 
    resources :photos, :except => [ :delete ]
  end
  delete '/albums/:album_id/photos/:id', to: 'photos#destroy', as: 'delete_album_photo'
  resources :profiles

  get '*all', to: 'application#check_bad_routes', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }

end

app/models/photo.rb
class Photo < ApplicationRecord
	validates :caption, presence: true, length: { in: 2..20 }
	validates_associated :album

	belongs_to :album

	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy ]
  before_action :check_photo_count, only: %i[ new create ]
  before_action :check_user_authenticity, except: :index
  skip_before_action :authenticate_user!, only: :index

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
    @album = Album.find(params[:album_id])
  end

  # GET /photos/1 or /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = @album.photos.build
  end

  def edit
  end

  def create
    @photo = Photo.new(photo_params.merge(album_id: @album.id))
    respond_to do |format|
      if @photo.save
        format.html { redirect_to album_photos_path(@album), notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to album_photos_path(@album), notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to album_photos_path, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def check_photo_count
      if @photos.present? && @photos.count > 25
        redirect_to album_photos_path(@album), notice: "Limit Exceeded."
      end
    end

    def check_user_authenticity
      @album = Album.find(params[:album_id])
      if @album.user_id != current_user.id
        redirect_to album_photos_path(@album), notice: "Execess denied."
      end
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:caption, :image ,:image_file_name)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for [@album, @photo], :html => { :multipart => true } do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :caption %>
    <%= form.text_field :caption, required:'', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, required:'', class: 'form-control-file' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>
<div class="card w-75 m-auto p-4">
	<%= render 'form', photo: @photo %>
</div>

<%= link_to 'Show', album_photo_path(@album), class: 'btn btn-info text-white' %>
<%= link_to 'Back', album_photos_path, class: 'btn btn-secondary text-white' %>

app/views/photos/index.html.erb
<h1>Photos</h1>
<div class="row m-auto">
    <% @album.photos.each do |photo| %>
      <div class="col-md-4">
        <div class="d-flex flex-column border m-2">
          <div class="img-w">
            <%= image_tag(photo.image.url, alt: photo.caption) %>
            <p class="caption text-center">Tag Line:<span> <%= photo.caption %></span></p>
          </div>
          <% if current_user && (current_user.id == @album.user_id) %>
            <div class="d-flex justify-content-around mb-3">
              <%= link_to 'Edit', edit_album_photo_path(@album, photo), class: 'btn btn-sm btn-secondary text-white' %> 
              <%= link_to 'Destroy', delete_album_photo_path(@album, photo), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger text-white' %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
    <% if @album.photos.count == 0 %>
      <h2 class="m-auto text-center">No Photo yet!</h2>
    <% end %>
</div>
<% if current_user && (current_user.id == @album.user_id) %>
  <%= link_to 'Upload New Photo', new_album_photo_path, class: 'btn btn-primary text-white' %>
<% end %>

app/views/photos/new.html.erb
<h1>New Photo</h1>
<div class="card w-75 m-auto p-4">
  <%= render 'form', photo: @photo %>
</div>

<%= link_to 'Back', album_photos_path, class: 'btn btn-secondary text-white' %>

app/views/photos/show.html.erb
<table class="table w-75 m-auto">
  <thead>
    <tr>
      <th>Caption</th>
      <th>Image</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @photo.caption %></td>
      <td><%= image_tag(@photo.image.url, alt: @photo.caption, :class=> 'w-50') %></td>
    </tr>
  </tbody>
</table>



<%= link_to 'Edit', edit_album_photo_path(@album), class: 'btn btn-info text-white' %>
<%= link_to 'Back', album_photos_path, class: 'btn btn-secondary text-white' %>